### ISSUE TITLE
If the import endpoints job fails it provides no feedback on what to fix

### ISSUE THREAD

**Issue by alkemann** [schibsted/spid-tech-docs#70]
"Fetching http://spp.dev/api/2/endpoints
Aborting import, since schema has changed. It no longer passes
our expectations for the data structure.

If this is just a new field to be ignored by the tech-docs
site, add it as an optional field to the schema in validate_raw.clj.
Otherwise, there's Clojure programming ahead."

This is not helpful.

**Comment by magnars** [comment]
The code in question also reports any added or removed fields, which would be more useful. So the change is probably breaking in a way that does not entail adding or removing fields. This is the expected data-structure:

https://github.com/schibsted/spid-tech-docs/blob/master/src/spid_docs/validate_raw.clj#L16-L32

```clj
(def Endpoint
  {:category [Str]
   :name Str
   :description Str
   :path Str
   :pathParameters [Str]
   :method Str
   :url Str
   :controller Str
   :defaultOutputFormat Str
   :validOutputFormats [Str]
   :httpMethods {(optional-key :GET) HttpMethod
                 (optional-key :POST) HttpMethod
                 (optional-key :DELETE) HttpMethod}
   :parameterDescriptions {Keyword Str}
   (optional-key :alias) {Keyword Str}
   (optional-key :deprecated) Str})
```

Looking at it, the most likely change is that you're now also using `PUT`. Could that be it?

In `diff_endpoints.clj` there is a `schema-is-valid?` function that calls `schema/check`. Replace that with `schema/validate` to get a detailed report of everything that is wrong. It is quite horrible to parse manually tho, which is why we tried to be more helpful in the first place.
